[settings]
experimental = true

[tools]
"github:uroybd/DotR" = { version = "1.0.3" }

[tasks.bootstrap]
description = "Bootstrap necessary configuration"
depends = "stow:adopt -m bootstrap bundle-default nushell-scripts"
depends_post = [
    { task = "dotr", args=["--profile", "default"] }
]

[tasks.packages]
description = "Provision System packages (Apt, Flatpak)"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to install" default="default"
'''
interactive = true
run = 'mise run -j 1 --raw packages:?* ${usage_update:+--update} ${usage_bundle}'


[tasks."packages:apt"]
description = "Provision Apt package bundles"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to install"
'''
run = './nu/install-packages.nu apt ${usage_update:+--update} ${usage_bundle}'


[tasks."packages:flatpak"]
description = "Provision Flatpak packages"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to provision" default="default"
'''
run = './nu/install-packages.nu flatpak ${usage_update:+--update} ${usage_bundle}'

[tasks."nix:rm"]
description = "Remove nix profile"
usage='arg "profile"               help="Specifies profile to remove"'
run = 'nix profile remove nix/{{ usage.profile }}'

[tasks."nix:cleanup"]
description = "Run nix-collect-garbage"
run = 'nix-collect-garbage'

[tasks."provision:minimal"]
description = "Provision minimal system"
usage = 'flag "-u --update" help="Enforce update of installed software"'
interactive = true
run = [
    'mise run -j 1 --raw packages:?* ${usage_update:+--update} default',
    'mise run nix ${usage_update:+--update} minimal',
    'mise run stow podman bundle-default',
    # 'mise run --raw setup:systemd-linger',
]

[tasks."provision:desktop"]
description = "Provision minimal system"
usage = 'flag "-u --update" help="Enforce update of installed software"'
interactive = true
run = [
    'mise run -j 1 --raw packages:?* ${usage_update:+--update} default desktop',
    'mise run nix ${usage_update:+--update} desktop',
    'mise run stow podman bundle-default bundle-desktop',
    # 'mise run --raw setup:systemd-linger',
]

[tasks.stow]
description = "Stow dotfiles packages"
usage = '''
arg "<packages>" help="Specify the package(s) to stow (eg: bundle-default, podman etc)" var=#true
'''
run = 'stow --no-folding -d stow -v -t ~ ${usage_packages}'
depends_post = [
    # Invoke tasks for each package: mise-tasks/<prefix>/<package>
    { task = "glob", args=["--prefix", "stow", "{{usage.packages}}"] }
]

[tasks."stow:delete"]
description = "Unstow dotfiles packages"
usage = '''
arg  "<packages>" help="Specify the package(s) to stow (eg: bundle-default, podman etc)" var=#true
'''
run = 'stow -D --no-folding -d stow -v -t ~ ${usage_packages}'
depends = [
    { task = "glob", env = {hookAction = "delete"}, args=["--prefix", "stow", "{{usage.packages}}"] }
]

[tasks.dotr]
description = "Run DotR deploy tasks (with templating)"
dir = '{{ config_root }}/dotr'
usage = '''
flag "--profile -P <profile>" help="Profile to use"
flag "--dry-run -d" help="Dry run"
'''
run = 'dotr deploy ${usage_dry_run:+--dry-run} --clean false -P ${usage_profile}'
