[tasks.packages]
description = "Provision System packages (Apt, Flatpak)"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to install" default="default"
'''
run = 'exec mise run --jobs=1 packages:?* ${usage_update:+--update} ${usage_bundle}'


[tasks."packages:apt"]
description = "Provision Apt package bundles"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to install"
'''
run = './nu/install-packages.nu apt ${usage_update:+--update} ${usage_bundle}'


[tasks."packages:flatpak"]
description = "Provision Flatpak packages"
usage = '''
flag "-u --update"          help="Update packages"
arg "[bundle]" var=#true    help="Specifies which software bundles to provision" default="default"
'''
run = './nu/install-packages.nu flatpak ${usage_update:+--update} ${usage_bundle}'


[tasks."nix:rm"]
description = "Remove nix profile"
usage='arg "profile"               help="Specifies profile to remove"'
run = 'nix profile remove nix/{{ usage.profile }}'


[tasks."nix:cleanup"]
description = "Run nix-collect-garbage"
run = 'nix-collect-garbage'


[tasks."provision:minimal"]
description = "Provision minimal system"
usage = 'flag "-u --update" help="Enforce update of installed software"'
raw = true
run = 'exec mise run --raw --jobs=1 packages:?* ${usage_update:+--update} defaut'


[tasks."provision:desktop"]
description = "Provision minimal system"
usage = 'flag "-u --update" help="Enforce update of installed software"'
raw = true
run = [
    'exec mise run --raw --jobs=1 packages:?* ${usage_update:+--update} default desktop',
    'exec mise run nix ${usage_update:+--update} desktop',
]
depends_post = [
    "setup:podman",
    "setup:keepassxc"
]


[tasks.bootstrap]
description = "Runs necessary tasks for the bootstrap stage"
depends = ["stow:adopt"]


[tasks."stow"]
description = "Stow directory structure"
run = "stow -v --no-folding ."


[tasks."stow:clean"]
description = "Unstow directory structure"
run = "stow -v --no-folding ."


[tasks."stow:adopt"]
description = "Stow adopt - adopts changes and stashes them (result is restored)"
run = [
    # Enforce ~/dotfiles git version rather than adopted during bootstrap (differs from default stow behaviour)
    # Basically we recreate links for .bashrc, .profile etc and stash adopted diff (moved by stow into ~/dotfiles).
    "stow -v --no-folding --adopt . && git stash push -m 'post stow --adopt changes'",
    "git restore ."
]


[tasks."setup:podman"]
description = "Setup podman"
usage = '''
flag "-c --cleanup"          help="Cleanup"
'''
raw = true
run = [
    'exec mise run setup:stow-nix-user-systemd ${usage_cleanup:+--cleanup} podman',
    'exec mise run setup:podman-delegate ${usage_cleanup:+--cleanup}'
]
