#!/usr/bin/env sh
#MISE description="Grant access to Secrets Service socket (GCR - gnome crypto)"

if ! ( flatpak info org.keepassxc.KeePassXC &>/dev/null ); then
    exit 0
fi

flatpak override --user --filesystem=xdg-run/gcr org.keepassxc.KeePassXC

# Integrate Brave to work with KeepassXC (all are flatpak)
if ( flatpak info com.brave.Browser &>/dev/null ); then
    curl -sS https://gist.githubusercontent.com/dennybaa/54aeaeaa89212fea14c98d5a82437be7/raw/0d62fe463e31d25398e595a5d0376a9f8d87bbd7/setup-brave-keepassxc.sh \
        | bash -s

    gum style --foreground 214 '!Note: Set Settings -> SSH Agent -> SSH_AUTH_SOCK to /run/user/1000/gcr/ssh'
fi
