#!/usr/bin/env bash
# Functions, this file is loaded for bash/zsh

# k3d
k3d() {
    if [[ "$1" == "cluster" && "$2" == "create" ]]; then
        if [[ ! "$*" == *"--k3s-arg"* ]]; then
            command k3d "$@" --k3s-arg '--kubelet-arg=feature-gates=KubeletInUserNamespace=true@server:*'
            return
        fi
    fi
    command k3d "$@"
}


# browse nvim
ed() {
    local args="${@:-.}"
    command nvim $args
}
