#!/bin/sh
. ~/.shell/lib
# Detect shell
_shell=$(_dot_shell)
_supported_shell=$(echo "zsh bash" | grep -qw $_shell && echo 'true' || echo 'false')

# Supported shell
if [ "$_supported_shell" = "true" ]; then
    # Load mise-en-place (early since it may provides tools for plugins)
    eval "$(mise activate $_shell)"

    # Load starship
    eval "$(starship init $_shell)"
fi

# Load antidote
shell_source ~/.shell/antidote zsh

# Cleanup
unset -v _shell _supported_shell

# Aliases
alias e="nvim"
