#!/bin/sh
. ~/.shell/lib

# Load tools
if shell_is bash zsh; then
    eval "$(mise activate $_shell)"
    eval "$(starship init $_shell)"
fi

# Source tools and functions
source_on ~/.shell/antidote zsh
source_on ~/.shell/functions bash zsh

# Load bash specific configuration
source_on ~/.shell/bash bash


# Aliases
alias e="nvim"
alias ta="tmux a"


## Note!: run unset_lib in caller to clean up lib functions
