"$schema" = "https://starship.rs/config-schema.json"

continuation_prompt = "[∙](fg:lavender) "
add_newline = true
follow_symlinks = true
palette = 'catppuccin_frappe'
format = """\
${hostname}\
(${sudo}${directory} [❯](blue bold) )\
(${custom.git_dirty}${git_branch} [❯](yellow bold) )\
($kubernetes [❯](teal bold) )\
$time\
$cmd_duration\
\n$character\
"""

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"


[profiles]

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
disabled = false
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 10
style = "red bold"

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
disabled = false

[cmd_duration]
show_milliseconds = true
format = "[ in $duration](pink)"
disabled = false
show_notifications = true
min_time = 10_000
min_time_to_notify = 45_000

[container]
format = '[$symbol \[$name\]]($style) '
symbol = "⬢"
style = "red bold dimmed"
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = true
use_logical_path = true
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "blue bold"
disabled = false
read_only = "🔒"
read_only_style = "red"
truncation_symbol = ""
home_symbol = "~"

[directory.substitutions]

[direnv]
format = "[$symbol$loaded/$allowed]($style) "
symbol = "direnv "
style = "bold bright-yellow"
disabled = true
detect_extensions = []
detect_env_vars = ["DIRENV_FILE"]
detect_files = [".envrc"]
detect_folders = []
allowed_msg = "allowed"
not_allowed_msg = "not allowed"
denied_msg = "denied"
loaded_msg = "loaded"
unloaded_msg = "not loaded"


[env_var]
disabled = true

[fill]
style = "bold black"
symbol = "."
disabled = true

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = "☁️  "
style = "bold blue"
disabled = true
detect_env_vars = []

[gcloud.region_aliases]

[gcloud.project_aliases]

[git_branch]
format = "[ $symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "yellow bold"
only_attached = false
always_show_remote = false
ignore_branches = ['master', 'main']
ignore_bare_repo = true
disabled = false

[hostname]
ssh_only = true
ssh_symbol = "🌐 "
trim_at = "."
detect_env_vars = []
format = "[$ssh_symbol$hostname]($style) in"
style = "green dimmed bold"
disabled = false

[hostname.aliases]

[kubernetes]
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style)'
style = "teal bold"
disabled = false
contexts = [
  { context_pattern = "k3d-.*", symbol = "⏚ " },
]

[kubernetes.context_aliases]

[kubernetes.user_aliases]

[memory_usage]
threshold = 75
format = "via $symbol[$ram( | $swap)]($style) "
style = "white bold dimmed"
symbol = "🐏 "
disabled = true

[sudo]
format = "[as $symbol]($style)"
symbol = "🧙 "
style = "bold maroon"
allow_windows = false
disabled = false

[time]
disabled = false
time_format = "%R"
format = ' $time '

[custom.git_dirty]
detect_folders = [".git"]
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
command = "[[ -n $(git status --porcelain) ]] && echo '✙'"
style = "yellow bold"
format = "([$output]($style))"
