#!/bin/bash

# Get primary (or 0:) display y pixel density pixels per mm
primary_ypixel_mm() {
  line=$(xrandr  --listmonitors | grep '+\*')
  if [ -z "$line" ]; then
    # use display number 0
    line=$(xrandr  --listmonitors | grep '0: ')
  fi
  echo "$line" | sed -E 's/.*x([0-9]+\/[0-9]+).*/\1/' | bc -l
}

ppmm=$(primary_ypixel_mm)
factor=1

if (( $(echo "$ppmm > 4.0 && $ppmm < 6.0" | bc -l) )); then
  factor=1.17
elif (( $(echo "$ppmm > 6.0" | bc -l) )); then
  factor=1.25
fi

gsettings set org.gnome.desktop.interface text-scaling-factor "$factor"
